//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessGenesisCodeLines.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GuessGenesisEntities2 : DbContext
    {
        public GuessGenesisEntities2()
            : base("name=GuessGenesisEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserAnswer> UserAnswers { get; set; }
    
        public virtual ObjectResult<getBestAnswer_Result> getBestAnswer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getBestAnswer_Result>("getBestAnswer");
        }
    }
}
