//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccruralScheduleItem
    {
        public int AccruralScheduleItemID { get; set; }
        public Nullable<int> AccruralScheduleID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int Frequency { get; set; }
        public int AdditionalAmount { get; set; }
        public Nullable<decimal> CarryOverPercentage { get; set; }
        public Nullable<int> FixedCarryOverAmount { get; set; }
    
        public virtual AccruralSchedule AccruralSchedule { get; set; }
    }
}
