//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeKeeper2.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeEventCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeEventCategory()
        {
            this.TimeEvents = new HashSet<TimeEvent>();
        }
    
        public int TimeEventCategoryID { get; set; }
        public string TimeEventCategoryName { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeEvent> TimeEvents { get; set; }
    }
}
