//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeKeeper2.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeEvent
    {
        public int TimeEventID { get; set; }
        public int TimeEventCategoryID { get; set; }
        public int TimeTrackerUserID { get; set; }
        public string TimeEventDescription { get; set; }
        public string TimeEventNotes { get; set; }
        public string TicketReference { get; set; }
    
        public virtual TimeTrackerUser TimeTrackerUser { get; set; }
        public virtual TimeEventCategory TimeEventCategory { get; set; }
    }
}
