//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeKeeper2.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeTracker3Entities : DbContext
    {
        public TimeTracker3Entities()
            : base("name=TimeTracker3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TimeEvent> TimeEvents { get; set; }
        public virtual DbSet<TimeEventCategory> TimeEventCategories { get; set; }
        public virtual DbSet<TimeTrackerUser> TimeTrackerUsers { get; set; }
    }
}
